services:
  mongo1:
    image: mongo:7
    container_name: mongo1
    command: mongod --replSet bdi-rs --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:7
    container_name: mongo2
    command: mongod --replSet bdi-rs --bind_ip_all
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db

  mongo3:
    image: mongo:7
    container_name: mongo3
    command: mongod --replSet bdi-rs --bind_ip_all
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: bdi-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password123
    volumes:
      - neo4j_data:/data

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  neo4j_data: